### PR TITLE
Rework routeDispatchTries + endpoint lookup for more intuitive 404/405 responses.

### LINKED ISSUE #51: Cask returns 405 for an undefined route that uses a method not used by other routes.
As tested with Scala 3 and cask 0.7.11

**Server definition**

```scala
class ServerRoutes(using cask.Logger) extends cask.Routes:
    @cask.get("/foo")
    def foo() = "get foo!"

    @cask.post("/bar")
    def bar() = "post bar!"

    initialize()


object server extends cask.Main:
    val allRoutes = Seq(ServerRoutes())
```

**Example queries with responses**

```
> curl -D - 'localhost:8080/foo' 
HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: text/plain; charset=utf-8
Content-Length: 3
Date: Sun, 16 May 2021 19:57:13 GMT

get foo!
> curl -D - 'localhost:8080/bar'
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Type: text/plain; charset=utf-8
Content-Length: 20
Date: Sun, 16 May 2021 19:57:16 GMT

Error 404: Not Found

> curl -D - -XPUT 'localhost:8080/baz'
HTTP/1.1 405 Method Not Allowed
Connection: keep-alive
Content-Type: text/plain; charset=utf-8
Content-Length: 29
Date: Sun, 16 May 2021 19:57:24 GMT

Error 405: Method Not Allowed
```

**Expected outcomes**

Request -> response 1 is expected
Request -> response 2 should be 405 but is 404
Request -> response 3 should be 404 but is 405

### PR DESCRIPTION
**Pull request by megri**
Prevent cask from responding with 405 for an undefined route.
Fixes #51.

Prior to this commit, `prepareRouteTries` created a mapping from
method-name to DispatchTrie (Map[String, DispatchTrie[…]]).

This commit instead creates a DispatchTrie[Map[String, …]],
basically an inversion of the previous result.

The updated tests in minimalApplication and minimalApplication2
have been updated to cover the differences.

### CODE REVIEW

**Comment by megri** [comment]
This PR is probably pretty stale by now. Still, it'd be nice to at least get some form of feedback on the hours spent..

**Comment by lihaoyi** [comment]
@megri could you provide a proper PR description of what your change is doing and how it fixes the problem? That would make it much easier to review and merge

**Comment by megri** [comment]
> @megri could you provide a proper PR description of what your change is doing and how it fixes the problem? That would make it much easier to review and merge

I updated the PR with the commit message of the final commit. There is some cleanup/unrelated commits in the PR as well. I can remove those if so desired.

**Comment by lihaoyi** [comment]
@megri looks great, sorry for the delay in getting to this. Have not been on top of maintenance last few months

**Pull request merged**
